name: Check data pack
on: [pull_request, push]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          show-progress: false
      - name: Validate commands
        uses: mcbeet/check-commands@v1
        with:
          source: .
          stats: true
